version: '3.7'
services:
    db:
        image: postgres:13.2
        container_name: db-postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: pass_demo
            POSTGRES_DB: db_demo

    db-test:
        image: postgres:13.2
        container_name: db-postgres-test
        restart: always
        ports:
          - 5439:5432
        environment:
          POSTGRES_PASSWORD: pass_demo_test
          POSTGRES_DB: db_demo_test

    backend_redis_test:
        image: redis:alpine
        container_name: db-redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --requirepass password
